/**
 * @param {number} rowIndex
 * @return {number[]}
 */
 var getRow = function(rowIndex) {
    if (rowIndex < 0) {
        return [];
    }

    var output = [];

    for (let i = 0; i <= rowIndex; i++) { //i=0; rowIndex=3; i++=4
        if (i === 0 || i === rowIndex) {
            output[i] = 1; // Set the first and last elements to 1 (the edges of Pascal's Triangle).
        } else {
            // Calculate the values in between using the previous row.
            output[i] = output[i - 1] * (rowIndex - i + 1) / i; // 2 * (3-3+1)/3=2/3
        }
    }

    return output; //[1,3,3,1]
};

//Test cases
console.log(getRow(0)); // Output: [1]
// Explanation: The 0th row of Pascal's Triangle is just [1].

console.log(getRow(1)); // Output: [1, 1]
// Explanation: The 1st row of Pascal's Triangle is [1, 1].

console.log(getRow(2)); // Output: [1, 2, 1]
// Explanation: The 2nd row of Pascal's Triangle is [1, 2, 1].
// It's generated by summing the adjacent elements in the previous row.

console.log(getRow(3)); // Output: [1, 3, 3, 1]
// Explanation: The 3rd row of Pascal's Triangle is [1, 3, 3, 1].
// It's generated using the formula as described in the code.

console.log(getRow(4)); // Output: [1, 4, 6, 4, 1]
// Explanation: The 4th row of Pascal's Triangle is [1, 4, 6, 4, 1].
// Each element is calculated based on the previous row.
